### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by yanlei-wei** [HondamunigePrasannaSilva/DiffDefence#2]
Hi, can you share this file? /equilibrium/seide/generative_models/silva/Project-Diffusion-Defense/config.yaml

**Comment by HondamunigePrasannaSilva** [comment]
Hi, the file that you are asking is on the main folder named **config.yaml**, i will correct the code as soon as possibile!
just correct the path with `config = utils.loadconfigYaml("./config.yaml")` and it should work!
